#!/bin/bash
REPO_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "${REPO_ROOT}" || exit 1

export PYTHONPATH=""

REPO_ROOT="$(git rev-parse --show-toplevel)"

BASHFILES=("dolint" "dotest" "git_hooks/pre-push")
PYTHON_BIN=()
for i in bin/* ; do
    head -n 1 "$i" | grep -q python
    if [ $? -eq 0 ] ; then
      PYTHON_BIN+=("$REPO_ROOT/bin/$(basename "$i")")
    else
      head -n 1 "$i" | grep -q bash
      if [ $? -eq 0 ] ; then
        BASHFILES+=("$i")
      else
        echo "Not linting: $i"
      fi
    fi
done

yapf -i -r --style="./style.yapf" "${PYTHON_BIN[@]}" ./lib/*
A=$?

pyflakes "${PYTHON_BIN[@]}" ./lib/*
B=$?

pushd lib &> /dev/null
PYTHONPATH="../tests" pylint --rcfile=../pylintrc "${PYTHON_BIN[@]}" ./* ../tests/*
C=$?
popd &> /dev/null

command -v shellcheck >/dev/null 2>&1 || { echo >&2 "I require shellcheck to lint bash files but it's not installed.  Aborting."; exit 1; }

shellcheck "${BASHFILES[@]}"
D=$?

for i in $A $B $C $D ; do
  if ! [ $i -eq 0 ] ; then
    exit $i
  fi
done
