#!/bin/bash

# avoid getting retorrentlib from a system-wide install
export PYTHONPATH=""

BIN="bin/is_seeded bin/remreffer bin/retorrent bin/symlinker"


pyflakes $BIN lib/*
pylint -E $BIN
(cd lib && pylint -E *)
(cd tests && pylint -E *)
