#!/bin/bash

PATH=$PATH:$HOME/doc/scripts

killall -9 xbmc &> /dev/null
killall -9 xbmc.bin &> /dev/null

DATE=`nicedatetime`
XBMCLOGDIR=$HOME/.xbmc/temp
LOGDIR=$HOME/logs

mkdir -p "$LOGDIR"
mkdir -p "$LOGDIR/xbmc-restarted"

echo `nicedatetime`" Restarted xbmc" >> $LOGDIR/xbmc-restarted.log

[ -f $XBMCLOGDIR/xbmc.log ] && mv $XBMCLOGDIR/xbmc.log $LOGDIR/xbmc-restarted/$DATE-xbmc-restarted.log
[ -f $XBMCLOGDIR/xbmc.old.log ] && mv $XBMCLOGDIR/xbmc.old.log $LOGDIR/xbmc-restarted/$DATE-xbmc-restarted.old.log

sleep 2

DISPLAY=:0 xbmc -fs & &> /dev/null 
