#!/usr/bin/python

# TODO : More testing. 
# TODO : Combine into obconf (?)
# TODO (Maybe) : Interactive 'which desktop' question
# TODO (Less likely) : Interactive 'which options' questions
import os
import subprocess
import sys

# cli uses inverse boolean to python
def xprop_exists():
	return not os.system('which xprop &> /dev/null')

if not xprop_exists():
	print >> sys.stderr, 'Could not find xprop. Possible Causes:' 
	print >> sys.stderr, ' - xprop and/or which aren\'t installed'
	print >> sys.stderr, ' - xprop and/or which aren\'t in your PATH'
	sys.exit(1)

print 'Now click on the application you want to configure!'
print 

s = subprocess.Popen(['xprop'], \
	stderr=subprocess.STDOUT, stdout=subprocess.PIPE).communicate()[0]

items = {'WM_CLASS':'"",""','WM_WINDOW_ROLE':'""','_NET_WM_WINDOW_TYPE':'""'}

for line in s.splitlines():
	for item in items.keys():
		if item in line:
			items[item] = line.split('=')[1].strip()

outitems = {	'name' 	: items['WM_CLASS'].split(',')[0].strip(),	\
				'class' : items['WM_CLASS'].split(',')[1].strip(),	\
				'role'	: items['WM_WINDOW_ROLE'], \
				'type'	: items['_NET_WM_WINDOW_TYPE'] }

# Always include both WM_CLASS entries
# Use the others if the previous are blank
outstring = '<application name=' + outitems['name'] + ' class=' + outitems['class'] 

if outitems['name'] == '""' and outitems['class'] == '""':
	outstring += ' role=' + outitems['role'] 
	if outitems['role'] == '""':
		outstring += ' type=' + outitems['type']
		
endstring = '> \n\t<desktop>1</desktop> \n\t<layer>normal</layer> \n\t<focus>no</focus> \n</application>'

print outstring + endstring

